"use client";

import { useState } from "react";
import Stepper from "@/components/Stepper";
import ExternalForm from "@/components/ExternalForm";
import InternalForm from "@/components/InternalForm";
import { TEMPLATES } from "@/lib/templates";
import { promptFor } from "@/lib/prompts";
import { generateDocx } from "@/lib/generate";
import { generatePdf } from "@/lib/pdfClient";
import {
  blankResume,
  schemaFor,
  type ExternalResume,
  type InternalResume,
  type ResumeData,
  type TemplateId,
} from "@/lib/schemas";

export type Audience = "employee" | "hr";

interface FieldError {
  path: string;
  message: string;
}

/** Per-template copy for the "get started" experience (intro, the two choice cards,
 *  the extraction-prompt steps and the paste-JSON hint). */
const START: Record<
  TemplateId,
  {
    sectionTitle: string;
    sectionSubtitle: string;
    boxA: { title: string; body: string; cta: string };
    boxB: { title: string; body: string; cta: string };
    promptSteps: string[];
    pasteSubtext: string;
  }
> = {
  external: {
    sectionTitle: "External Profile",
    sectionSubtitle: "Generate a client-ready InfoBeans profile for external candidates.",
    boxA: {
      title: "Generate from Candidate Resume",
      body: "Upload the candidate's resume to generate a standardized InfoBeans profile ready for client submission.",
      cta: "Upload resume",
    },
    boxB: {
      title: "Create a Profile from Scratch",
      body: "Start with a blank external profile template and fill in the required details to generate a profile in the InfoBeans standard format.",
      cta: "Get started",
    },
    promptSteps: [
      "Click “Copy LLM Prompt,” then paste the prompt into Gemini together with the candidate's profile PDF.",
      "Once Gemini generates the JSON, copy the entire response.",
      "Click “I Have the JSON”, paste the JSON, and click “Continue”.",
    ],
    pasteSubtext: "Paste the JSON generated by Gemini for the External Profile template, then click “Continue”.",
  },
  internal: {
    sectionTitle: "Internal Profile",
    sectionSubtitle: "Generate an internal InfoBeans profile.",
    boxA: {
      title: "Update an Existing Profile",
      body: "Already have an InfoBeans profile? Upload your latest version to update your information and generate a refreshed profile in standard format.",
      cta: "Upload existing profile",
    },
    boxB: {
      title: "Create a Profile from Scratch",
      body: "Creating your profile for the first time? Start with a blank template and build your InfoBeans profile section by section.",
      cta: "Get started",
    },
    promptSteps: [
      "Click “Copy LLM Prompt” and paste it into Gemini, along with your existing profile PDF.",
      "Once Gemini generates the JSON, copy the entire response.",
      "Click “I Have the JSON”, paste the JSON, and click “Continue”.",
    ],
    pasteSubtext: "Paste the JSON generated by Gemini for the Internal Profile template, then click “Continue”.",
  },
};

export default function ProfileWorkflow({ audience }: { audience: Audience }) {
  // HR sees every template; employees are limited to the internal profile.
  const isEmployee = audience === "employee";
  const templates = isEmployee ? TEMPLATES.filter((t) => t.id === "internal") : TEMPLATES;
  const lockedTemplate = templates.length === 1 ? templates[0].id : null;
  const stepLabels = isEmployee
    ? ["Start", "Provide data", "Review & Generate"]
    : ["Template", "Provide data", "Review & Generate"];

  const [step, setStep] = useState(0);
  const [templateId, setTemplateId] = useState<TemplateId | null>(lockedTemplate);
  // Step 0 has two views once a template is chosen: the choice cards and the extraction-prompt screen.
  const [showPromptScreen, setShowPromptScreen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [jsonText, setJsonText] = useState("");
  const [errors, setErrors] = useState<FieldError[] | null>(null);
  const [data, setData] = useState<ResumeData | null>(null);
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [generated, setGenerated] = useState<string | null>(null);

  const start = templateId ? START[templateId] : null;

  const copyPrompt = async () => {
    if (!templateId) return;
    await navigator.clipboard.writeText(promptFor(templateId));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const validateJson = (text: string): boolean => {
    if (!templateId) return false;
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch (e) {
      setErrors([{ path: "(document)", message: `Not valid JSON: ${e instanceof Error ? e.message : String(e)}` }]);
      return false;
    }
    const result = schemaFor(templateId).safeParse(parsed);
    if (!result.success) {
      setErrors(
        result.error.issues.map((issue) => ({
          path: issue.path.length ? issue.path.join(".") : "(root)",
          message: issue.message,
        })),
      );
      return false;
    }
    setErrors(null);
    setData(result.data);
    return true;
  };

  const handleJsonChange = (text: string) => {
    setJsonText(text);
    if (errors) setErrors(null);
  };

  const continueToReview = () => {
    if (validateJson(jsonText)) setStep(2);
  };

  const startBlankForm = () => {
    if (!templateId) return;
    setData(blankResume(templateId));
    setErrors(null);
    setJsonText("");
    goTo(2);
  };

  const changeTemplate = () => {
    setTemplateId(null);
    setShowPromptScreen(false);
  };

  const handleGenerate = async (format: "docx" | "pdf" | "both") => {
    if (!templateId || !data) return;
    setGenerating(true);
    setGenerateError(null);
    setGenerated(null);
    try {
      const candidate = (data as { name?: string }).name?.trim().replace(/\s+/g, "_") || "resume";
      const baseName = `${candidate}_${templateId}_profile`;
      if (format === "docx" || format === "both") {
        await generateDocx(templateId, data, `${baseName}.docx`);
      }
      if (format === "pdf" || format === "both") {
        await generatePdf(templateId, data, `${baseName}.pdf`);
      }
      setGenerated(
        format === "docx"
          ? "DOCX downloaded — check your downloads."
          : format === "pdf"
            ? "PDF downloaded — check your downloads."
            : "DOCX and PDF downloaded — check your downloads.",
      );
    } catch (e) {
      setGenerateError(e instanceof Error ? e.message : String(e));
    } finally {
      setGenerating(false);
    }
  };

  const goTo = (target: number) => {
    setStep(target);
    setGenerateError(null);
    setGenerated(null);
  };

  return (
    <div className="w-full text-ink">
      {/* hero */}
      <section className="border-b border-hairline bg-cream">
        <div className="mx-auto max-w-3xl px-4 py-12 text-center">
          {!isEmployee && (
            <span className="inline-flex items-center gap-2 rounded-full bg-brand-50 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-brand-700">
              <span className="h-1.5 w-1.5 rounded-full bg-brand-500" />
              InfoBeans Profiles · HR
            </span>
          )}
          <h1 className={`text-3xl font-bold tracking-tight text-ink-dark sm:text-4xl ${isEmployee ? "" : "mt-4"}`}>
            {isEmployee ? "Infobeans Profile Generator" : "Profile Generator"}
          </h1>
          <p className="mx-auto mt-3 max-w-xl text-sm text-ink-light sm:text-base">
            {isEmployee ? (
              "Your profile is a key branding tool that enables us to showcase your expertise to prospective clients and identify opportunities for role enrichment within the organization."
            ) : (
              <>
                Turn an LLM&apos;s JSON into a perfectly branded InfoBeans profile. Pick a template, then upload or start
                from scratch to generate a DOCX — <span className="font-semibold text-brand-500">Creating WOW!</span>
              </>
            )}
          </p>
        </div>
      </section>

      <main className="mx-auto max-w-3xl px-4 py-10">
        <div className="mb-10">
          <Stepper current={step} onNavigate={goTo} labels={stepLabels} />
        </div>

        {/* ---------- STEP 0: template picker (HR, before a choice) ---------- */}
        {step === 0 && !templateId && !isEmployee && (
          <div className="animate-fade-up grid gap-4 sm:grid-cols-2">
            {templates.map((t) => (
              <button
                key={t.id}
                type="button"
                onClick={() => setTemplateId(t.id)}
                className="group relative overflow-hidden rounded-xl border border-gray-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"
              >
                <span className="absolute inset-x-0 top-0 h-1 bg-transparent transition-colors group-hover:bg-brand-200" />
                <div className="mb-2 font-semibold text-ink-dark">{t.name}</div>
                <p className="mb-3 text-sm text-ink-light">{t.description}</p>
                <div className="flex flex-wrap gap-1.5">
                  {t.highlights.map((h) => (
                    <span key={h} className="rounded-full bg-brand-50 px-2 py-0.5 text-xs font-medium text-brand-700">
                      {h}
                    </span>
                  ))}
                </div>
              </button>
            ))}
          </div>
        )}

        {/* ---------- STEP 0: start experience (after a template is chosen) ---------- */}
        {step === 0 && templateId && start && (
          <div className="animate-fade-up space-y-6">
            {!isEmployee && (
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h2 className="text-xl font-bold text-ink-dark">{start.sectionTitle}</h2>
                  <p className="mt-1 text-sm text-ink-light">{start.sectionSubtitle}</p>
                </div>
                <button
                  type="button"
                  onClick={changeTemplate}
                  className="shrink-0 rounded-md px-2 py-1 text-sm font-medium text-ink-light hover:text-ink"
                >
                  ← Change template
                </button>
              </div>
            )}

            {!showPromptScreen ? (
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="flex flex-col rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                  <h3 className="mb-2 font-semibold text-ink-dark">{start.boxA.title}</h3>
                  <p className="mb-5 flex-1 text-sm text-ink-light">{start.boxA.body}</p>
                  <button
                    type="button"
                    onClick={() => setShowPromptScreen(true)}
                    className="self-start rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600"
                  >
                    {start.boxA.cta}
                  </button>
                </div>
                <div className="flex flex-col rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                  <h3 className="mb-2 font-semibold text-ink-dark">{start.boxB.title}</h3>
                  <p className="mb-5 flex-1 text-sm text-ink-light">{start.boxB.body}</p>
                  <button
                    type="button"
                    onClick={startBlankForm}
                    className="self-start rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600"
                  >
                    {start.boxB.cta}
                  </button>
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                  <h3 className="mb-3 font-semibold text-ink-dark">Get the extraction prompt</h3>
                  <ol className="mb-4 list-decimal space-y-2 pl-5 text-sm text-ink-light">
                    {start.promptSteps.map((s, i) => (
                      <li key={i}>{s}</li>
                    ))}
                  </ol>
                  <div className="flex items-center gap-3">
                    <button
                      type="button"
                      onClick={copyPrompt}
                      className="rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600"
                    >
                      {copied ? "Copied ✓" : "Copy LLM Prompt"}
                    </button>
                    <button
                      type="button"
                      onClick={() => goTo(1)}
                      className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-ink hover:bg-gray-50"
                    >
                      I Have the JSON →
                    </button>
                  </div>
                  <details className="mt-4">
                    <summary className="cursor-pointer text-xs text-ink-light hover:text-ink">Preview prompt</summary>
                    <pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap rounded-md bg-ink-dark p-3 text-xs text-gray-100">
                      {promptFor(templateId)}
                    </pre>
                  </details>
                </div>
                <button
                  type="button"
                  onClick={() => setShowPromptScreen(false)}
                  className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-ink hover:bg-gray-50"
                >
                  ← Back
                </button>
              </div>
            )}
          </div>
        )}

        {/* ---------- STEP 1: paste JSON ---------- */}
        {step === 1 && templateId && start && (
          <div className="animate-fade-up space-y-4">
            <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
              <h2 className="mb-2 font-semibold text-ink-dark">Paste the JSON</h2>
              <p className="mb-3 text-sm text-ink-light">{start.pasteSubtext}</p>
              <textarea
                value={jsonText}
                onChange={(e) => handleJsonChange(e.target.value)}
                spellCheck={false}
                rows={16}
                placeholder='{"name": "…", "jobTitle": "…", …}'
                className="w-full rounded-md border border-gray-300 p-3 font-mono text-xs text-ink focus:border-brand-500 focus:outline-none focus:ring-1 focus:ring-brand-500"
              />
              {errors && (
                <div className="mt-3 rounded-md border border-brand-200 bg-brand-50 p-3">
                  <p className="mb-2 text-sm font-semibold text-brand-700">
                    {errors.length} validation {errors.length === 1 ? "issue" : "issues"}:
                  </p>
                  <ul className="space-y-1 text-sm text-brand-700">
                    {errors.map((err, i) => (
                      <li key={i}>
                        <code className="rounded bg-brand-100 px-1 py-0.5 text-xs">{err.path}</code> — {err.message}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
            <div className="flex justify-between">
              <button
                type="button"
                onClick={() => {
                  setShowPromptScreen(true);
                  goTo(0);
                }}
                className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-ink hover:bg-gray-50"
              >
                ← Back
              </button>
              <button
                type="button"
                onClick={continueToReview}
                disabled={!jsonText.trim()}
                className="rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600 disabled:opacity-40"
              >
                Continue →
              </button>
            </div>
          </div>
        )}

        {/* ---------- STEP 2: review & generate ---------- */}
        {step === 2 && templateId && data && (
          <div className="animate-fade-up space-y-5">
            {templateId === "external" ? (
              <ExternalForm data={data as ExternalResume} onChange={(d) => setData(d)} />
            ) : (
              <InternalForm data={data as InternalResume} onChange={(d) => setData(d)} />
            )}

            {generateError && (
              <div className="whitespace-pre-wrap rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">
                {generateError}
              </div>
            )}
            {generated && !generateError && (
              <div className="rounded-md border border-green-200 bg-green-50 p-3 text-sm text-green-700">{generated}</div>
            )}

            <div className="flex flex-wrap items-center justify-between gap-3">
              <button
                type="button"
                onClick={() => goTo(1)}
                className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-ink hover:bg-gray-50"
              >
                ← Back
              </button>
              <button
                type="button"
                onClick={() => handleGenerate("docx")}
                disabled={generating}
                className="rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600 disabled:opacity-50"
              >
                {generating ? "Generating…" : "DOCX ↓"}
              </button>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
